import os
import asyncio
import urllib.parse
import json
import io
from fastapi import FastAPI, Request, BackgroundTasks, HTTPException
from fastapi.responses import HTMLResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
import httpx

# LINE SDK Legacy Imports
from linebot import LineBotApi, WebhookHandler
from linebot.exceptions import InvalidSignatureError
from linebot.models import (
    MessageEvent, TextMessage, TextSendMessage, 
    ImageMessage, AudioMessage, LocationMessage, VideoMessage,
    QuickReply, QuickReplyButton, LocationAction,
    ImageSendMessage, AudioSendMessage
)
from PIL import Image, ImageDraw, ImageFont
from gtts import gTTS
import agents

app = FastAPI(title="Anshin Otasuke Agent Backend")

# State Management (In-Memory for hackathon)
class AppState:
    def __init__(self):
        self.emergency_mode = False
        self.show_overlay = False
        self.document_data = None
        self.logs = []
        self.route_coordinates = None
        self.route_steps = None
        self.last_latitude = 35.6585
        self.last_longitude = 139.7013
        self.active_hazard = "other"
        self.user_id = None
        self.base_url = "http://localhost:8080"

    def add_log(self, text: str, log_type: str = "info"):
        self.logs.append({"text": text, "type": log_type})
        print(f"[{log_type.upper()}] {text}")

    def reset(self):
        self.emergency_mode = False
        self.show_overlay = False
        self.document_data = None
        self.route_coordinates = None
        self.route_steps = None
        self.active_hazard = "other"
        # keep last 5 logs for stability
        self.logs = self.logs[-5:]
        self.add_log("System state reset.", "info")

state = AppState()
state.add_log("Anshin Otasuke Agent initialized.", "info")

def save_user_id(event):
    if hasattr(event, 'source') and hasattr(event.source, 'user_id'):
        state.user_id = event.source.user_id

# Serve Frontend static files
os.makedirs("static", exist_ok=True)
app.mount("/dashboard", StaticFiles(directory="static", html=True), name="static")

@app.get("/")
async def redirect_to_dashboard():
    return HTMLResponse("<script>window.location.href='/dashboard/index.html'</script>")

@app.get("/api/status")
async def get_status():
    status_data = {
        "emergency_mode": state.emergency_mode,
        "show_overlay": state.show_overlay,
        "document_data": state.document_data,
        "logs": state.logs,
        "route_coordinates": state.route_coordinates,
        "route_steps": state.route_steps
    }
    if state.show_overlay:
        state.show_overlay = False
    return JSONResponse(status_data)

# Helper function to generate direct single-click Google Calendar Add URLs
def get_google_calendar_url(title: str, deadline: str, summary: str) -> str:
    base_url = "https://calendar.google.com/calendar/render?action=TEMPLATE"
    date_formatted = "20260731" 
    
    params = {
        "text": f"Anshin Otasuke: {title}",
        "details": f"{summary}\n\nAutomatically generated by Anshin Otasuke AI Agent.",
        "dates": f"{date_formatted}/{date_formatted}"
    }
    return f"{base_url}&{urllib.parse.urlencode(params)}"

def generate_safety_card_pillow(shelter_name: str, hazard_type: str, steps: list) -> bytes:
    # Create a 600x600 image with a warm alert background
    img = Image.new("RGB", (600, 600), "#fff5f5")
    draw = ImageDraw.Draw(img)
    
    # Draw top alert banner
    draw.rectangle([(0, 0), (600, 80)], fill="#ff4757")
    
    # Try to load fonts safely
    font_title = None
    font_body = None
    font_bold = None
    
    font_paths = [
        "/System/Library/Fonts/Helvetica.ttc",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
        "/usr/share/fonts/truetype/freefont/FreeSansBold.ttf"
    ]
    for path in font_paths:
        if os.path.exists(path):
            try:
                font_title = ImageFont.truetype(path, 22)
                font_body = ImageFont.truetype(path, 15)
                font_bold = ImageFont.truetype(path, 17)
                break
            except:
                pass
                
    if not font_title:
        font_title = ImageFont.load_default()
        font_body = ImageFont.load_default()
        font_bold = ImageFont.load_default()
        
    draw.text((20, 28), "⚠️ EMERGENCY SAFETY ROUTE", fill="#ffffff", font=font_title)
    
    # Draw Hazard Type
    draw.text((30, 110), "🚨 DETECTED HAZARD:", fill="#2f3542", font=font_bold)
    draw.text((35, 138), hazard_type.upper(), fill="#ff4757", font=font_title)
    
    # Draw Shelter Info Box
    draw.rectangle([(30, 190), (570, 285)], fill="#e3faf2", outline="#2ed573", width=2)
    draw.text((50, 205), "📍 ASSIGNED SHELTER:", fill="#2ed573", font=font_bold)
    draw.text((50, 238), shelter_name, fill="#2f3542", font=font_title)
    
    # Draw Steps
    draw.text((30, 310), "🏃 WALKING DIRECTIONS:", fill="#2f3542", font=font_bold)
    y = 345
    for idx, step in enumerate(steps[:3]):
        words = step.split()
        current_line = []
        lines = []
        for word in words:
            if len(" ".join(current_line + [word])) < 50:
                current_line.append(word)
            else:
                lines.append(" ".join(current_line))
                current_line = [word]
        lines.append(" ".join(current_line))
        
        for line_idx, line in enumerate(lines):
            prefix = f"{idx + 1}. " if line_idx == 0 else "   "
            draw.text((45, y), f"{prefix}{line}", fill="#57606f", font=font_body)
            y += 20
        y += 8
        
    # Draw Footer
    draw.text((30, 545), "Shared automatically with your caregiver network.", fill="#a4b0be", font=font_body)
    
    # Save to bytes
    out = io.BytesIO()
    img.save(out, format="PNG")
    return out.getvalue()

def find_dynamic_shelter_via_gemini(lat: float, lon: float, address: str, hazard: str) -> dict:
    """
    Uses Gemini to dynamically identify a real, local evacuation center or public park
    suitable for the active hazard, close to the user's live coordinates.
    """
    if agents.IS_OFFLINE:
        return {
            "name": "Local District Safety Shelter",
            "lat": lat + 0.002,
            "lon": lon + 0.002,
            "steps": [
                "Proceed north toward the main main crossing.",
                "Turn right and walk 200m to the designated municipal shelter."
            ]
        }
        
    try:
        prompt = f"""
        The user is located at coordinates ({lat}, {lon}) which corresponds to the address: "{address}".
        An active emergency hazard of type "{hazard}" has been detected.
        
        Identify a real, suitable emergency evacuation shelter, public park, or safety zone near this location.
        Return a JSON object in English with the following keys.
        Do not wrap it in markdown like ```json or ```.
        
        JSON Keys:
        - name: The name of the real shelter (e.g. "Mito City Joto Elementary School" or "Shinjuku Gyoen National Garden")
        - lat: Estimated latitude of the shelter (should be near the user's coordinates, e.g. within 1-2 km)
        - lon: Estimated longitude of the shelter (should be near the user's coordinates, e.g. within 1-2 km)
        - steps: A list of 2-3 walking step directions from the user's location to the shelter.
        """
        
        model = agents.genai.GenerativeModel("models/gemini-3.5-flash")
        response = model.generate_content(prompt)
        text = response.text.strip()
        if text.startswith("```"):
            text = text.split("```")[1]
            if text.startswith("json"):
                text = text[4:]
                
        return json.loads(text.strip())
    except Exception as e:
        print(f"[ERROR] Dynamic shelter generation failed: {e}")
        # Fallback to Shibuya Jinnan
        return {
            "name": "Shibuya Jinnan Elementary School",
            "lat": 35.6631,
            "lon": 139.7001,
            "steps": [
                "Proceed toward Shibuya Jinnan area.",
                "Head to Jinnan Elementary School."
            ]
        }

# Setup LINE SDK Client & Webhook Handler
LINE_CHANNEL_SECRET = os.getenv("LINE_CHANNEL_SECRET")
LINE_CHANNEL_ACCESS_TOKEN = os.getenv("LINE_CHANNEL_ACCESS_TOKEN")

line_bot_api = None
handler = None

if LINE_CHANNEL_SECRET and LINE_CHANNEL_ACCESS_TOKEN:
    line_bot_api = LineBotApi(LINE_CHANNEL_ACCESS_TOKEN)
    handler = WebhookHandler(LINE_CHANNEL_SECRET)
    state.add_log("LINE Bot API and Webhook Handler successfully configured.", "success")
else:
    state.add_log("LINE credentials missing. Running Webhook in OFFLINE/MOCK mode.", "warning")

SHELTERS = [
    {
        "name": "Shibuya Jinnan Elementary School",
        "lat": 35.6631,
        "lon": 139.7001,
        "hazard_types": ["earthquake", "siren", "other"],
        "steps": [
            "Head north on Inokashira-dori street from your location.",
            "Pass Shibuya Loft/Disney Store and go straight at Organ-zaka junction.",
            "Turn left at Shibuya Jinnan Post Office junction.",
            "Go straight up the hill for 150m. Shibuya Jinnan Elementary School shelter will be on your left."
        ]
    },
    {
        "name": "Shibuya Ward Office",
        "lat": 35.6618,
        "lon": 139.6975,
        "hazard_types": ["fire", "siren", "other"],
        "steps": [
            "Head northwest from your location toward Udagawacho.",
            "Pass the Shibuya Ward Public Hall on your right.",
            "Shibuya Ward Office main shelter entrance is directly ahead."
        ]
    },
    {
        "name": "Yoyogi Park",
        "lat": 35.6717,
        "lon": 139.6949,
        "hazard_types": ["typhoon", "earthquake", "other"],
        "steps": [
            "Head north along Koen-dori street toward Yoyogi National Gymnasium.",
            "Cross the Harajuku/Yoyogi entry gateway.",
            "Proceed to the central open grass area of Yoyogi Park."
        ]
    }
]

def find_nearest_shelter(lat: float, lon: float, hazard: str = "other") -> dict:
    hazard = hazard.lower()
    
    # Map hazard string to specific hazard types
    target_hazard = "other"
    if "earthquake" in hazard:
        target_hazard = "earthquake"
    elif "fire" in hazard:
        target_hazard = "fire"
    elif "siren" in hazard:
        target_hazard = "siren"
    elif "typhoon" in hazard:
        target_hazard = "typhoon"
        
    best_shelter = None
    min_dist = float('inf')
    
    for s in SHELTERS:
        if target_hazard in s["hazard_types"] or "other" in s["hazard_types"]:
            dist = (lat - s["lat"])**2 + (lon - s["lon"])**2
            if dist < min_dist:
                min_dist = dist
                best_shelter = s
                
    return best_shelter or SHELTERS[0]


# helper function for synchronous trigger of emergency
def trigger_emergency_flow_sync(siren_result):
    state.emergency_mode = True
    state.show_overlay = True
    state.active_hazard = siren_result.get("alert_type", "other")
    state.add_log(f"Emergency detected: {siren_result['alert_type']} (Severity: {siren_result['severity']})", "danger")
    state.add_log(f"Announcement: {siren_result['announcement_summary']}", "danger")
    
    # Generate a default mock route for the simulator so map functions correctly
    shelter = find_nearest_shelter(state.last_latitude, state.last_longitude, state.active_hazard)
    state.route_coordinates = [
        [state.last_latitude, state.last_longitude],
        [(state.last_latitude + shelter["lat"])/2.0, (state.last_longitude + shelter["lon"])/2.0],
        [shelter["lat"], shelter["lon"]]
    ]
    state.route_steps = shelter["steps"]
    state.add_log(f"Nearest shelter identified: {shelter['name']}. Evacuation route generated.", "success")
    state.add_log("Emergency warning: Sent urgent alert to Hana Yamada's family.", "danger")

# Simulator POST API
class SimRequest(BaseModel):
    event_type: str

@app.post("/api/simulate")
async def trigger_simulate(req: SimRequest):
    event = req.event_type
    
    if event == "reset":
        state.reset()
        return {"status": "success", "message": "State reset successfully."}
        
    elif event == "invoice":
        state.reset()
        state.add_log("Simulator: Received photo from Hana Yamada on LINE.", "info")
        state.add_log("Sending image to parser agent (Gemini 1.5 Flash)...", "info")
        
        doc_result = agents.analyze_document(image_data=None)
        doc_result["google_calendar_link"] = get_google_calendar_url(
            doc_result.get("title", "Premium Notice"),
            doc_result.get("deadline", "July 31, 2026"),
            doc_result.get("summary", "")
        )
        
        doc_result["status"] = "pending"
        state.document_data = doc_result
        state.add_log(f"Analysis successful: {doc_result['title']} detected.", "success")
        state.add_log(f"【Summary】: {doc_result['summary']}", "success")
        state.add_log(f"Google Integration: Generated single-click Google Calendar Add URL.", "success")
        state.add_log(f"Calendar: Created reminder task due on {doc_result['deadline']}.", "info")
        
        # Add PayPay link logging
        paypay_link = f"{state.base_url}/dashboard/paypay.html?amount={doc_result.get('amount', 4200)}&issuer={urllib.parse.quote(doc_result.get('issuer', 'Premium Notice'))}"
        state.add_log(f"PayPay Integration: Generated single-click payment redirect: {paypay_link}", "success")
        
        return {"status": "success", "message": "Invoice simulation completed successfully."}
        
    elif event == "siren":
        state.reset()
        state.add_log("Simulator: Emergency disaster warning siren detected.", "warning")
        state.add_log("Sending audio to disaster analysis agent...", "info")
        
        siren_result = agents.analyze_siren(audio_data=None)
        trigger_emergency_flow_sync(siren_result)
        
        return {"status": "success", "message": "Emergency alert simulation active."}
        
    elif event == "eew":
        state.reset()
        state.add_log("Simulator: External JMA Earthquake Early Warning notification received.", "warning")
        state.add_log("Broadcasting urgent alert push to senior's LINE account...", "info")
        
        # Trigger the EEW warning flow
        siren_mock = {
            "alert_type": "JMA Earthquake Warning",
            "announcement_summary": "Major shaking expected nearby. Drop, cover, and hold on immediately.",
            "severity": "Extremely High"
        }
        trigger_emergency_flow_sync(siren_mock)
        
        # Push the LINE warning and ask for location immediately if user_id is set
        if line_bot_api and state.user_id:
            try:
                reply_text = (
                    f"🚨 EMERGENCY DISASTER WARNING (EEW)\n"
                    f"━━━━━━━━━━━━━━━━━━━\n"
                    f"A strong earthquake has been detected near Tokyo with Seismic Intensity 5 Upper.\n\n"
                    f"Please tap the button below to share your location immediately so I can calculate your evacuation route."
                )
                quick_reply = QuickReply(items=[
                    QuickReplyButton(action=LocationAction(label="📍 Share Location"))
                ])
                line_bot_api.push_message(
                    state.user_id, 
                    TextSendMessage(text=reply_text, quick_reply=quick_reply)
                )
                state.add_log("Successfully pushed urgent LINE location request to user device.", "success")
            except Exception as e:
                state.add_log(f"Failed to push LINE alert: {e}", "danger")
        else:
            state.add_log("LINE User ID not captured yet. Pushed alert bypassed (Simulated). Send a message on LINE first to capture ID.", "warning")
            
        return {"status": "success", "message": "JMA EEW Alert Simulation active."}
        
    else:
        raise HTTPException(status_code=400, detail="Invalid event type")

class PayRequest(BaseModel):
    amount: int
    issuer: str

@app.post("/api/pay")
async def pay_bill(req: PayRequest):
    state.add_log(f"PayPay: Hana successfully paid ¥{req.amount:,} to {req.issuer} via PayPay.", "success")
    if state.document_data:
        state.document_data["status"] = "paid"
    state.add_log("Task cleared: Bill payment verified and archived.", "success")
    return {"status": "success", "message": "Payment recorded successfully."}


# LINE Webhook Handlers (Only active when credentials are set)
if handler:
    @handler.add(MessageEvent, message=TextMessage)
    def handle_text_message(event):
        save_user_id(event)
        text = event.message.text.strip()
        reply_token = event.reply_token
        state.add_log(f"LINE: Received text '{text}' from Hana.", "info")
        
        if "emergency" in text.lower() or "alert" in text.lower() or "siren" in text.lower():
            # Trigger Emergency
            siren_mock = {
                "alert_type": "LINE Emergency Request",
                "announcement_summary": "Manual emergency trigger received from user device.",
                "severity": "High"
            }
            trigger_emergency_flow_sync(siren_mock)
            
            reply_text = (
                "⚠️ EMERGENCY ALERT ACTIVE!\n"
                "━━━━━━━━━━━━━━━━━━━\n"
                "Please share your live location using the button below so I can find the nearest safe evacuation shelter for you."
            )
            quick_reply = QuickReply(items=[
                QuickReplyButton(action=LocationAction(label="📍 Share Location"))
            ])
            line_bot_api.reply_message(reply_token, TextSendMessage(text=reply_text, quick_reply=quick_reply))
        elif "reset" in text.lower():
            state.reset()
            reply_text = "Guardian System has been reset. Back to normal monitoring."
            line_bot_api.reply_message(reply_token, TextSendMessage(text=reply_text))
        else:
            reply_text = (
                "Hello! I am your Anshin Guardian. 👵🛡️\n"
                "━━━━━━━━━━━━━━━━━━━\n"
                "How can I help you today?\n\n"
                "📄 Photo of document\n"
                "➔ I will simplify it.\n\n"
                "🎙️ Voice message / Video\n"
                "➔ I will scan for sirens/warnings.\n\n"
                "📍 Share Location\n"
                "➔ I will update your family's map.\n\n"
                "🚨 Type 'Emergency'\n"
                "➔ Trigger safety alerts."
            )
            line_bot_api.reply_message(reply_token, TextSendMessage(text=reply_text))

    @handler.add(MessageEvent, message=ImageMessage)
    def handle_image_message(event):
        save_user_id(event)
        reply_token = event.reply_token
        message_id = event.message.id
        state.add_log("LINE: Received image from Hana. Downloading contents...", "info")
        
        try:
            message_content = line_bot_api.get_message_content(message_id)
            image_bytes = b""
            for chunk in message_content.iter_content():
                image_bytes += chunk
                
            state.add_log("Image downloaded. Running Gemini Document Agent...", "info")
            
            # Execute Gemini OCR Analysis
            doc_result = agents.analyze_document(image_bytes)
            
            # Inject Google Calendar single-click url integration
            doc_result["google_calendar_link"] = get_google_calendar_url(
                doc_result.get("title", "Document Notice"),
                doc_result.get("deadline", "July 31, 2026"),
                doc_result.get("summary", "")
            )
            
            doc_result["status"] = "pending"
            state.document_data = doc_result
            state.add_log(f"Analysis successful: {doc_result['title']} detected.", "success")
            state.add_log(f"【Summary】: {doc_result['summary']}", "success")
            state.add_log(f"Google Integration: Generated single-click Google Calendar Add URL.", "success")
            
            # Construct simulated PayPay link
            paypay_link = f"{state.base_url}/dashboard/paypay.html?amount={doc_result.get('amount', 4200)}&issuer={urllib.parse.quote(doc_result.get('issuer', 'Shibuya Central Hospital'))}"
            
            # Reply result back on LINE
            reply_text = (
                f"📄 DOCUMENT ANALYZED\n"
                f"━━━━━━━━━━━━━━━━━━━\n"
                f"🔔 Title: {doc_result['title']}\n"
                f"📂 Category: {doc_result['type']}\n"
                f"🏢 Issuer: {doc_result['issuer']}\n"
                f"━━━━━━━━━━━━━━━━━━━\n"
                f"💡 Simple Explanation:\n"
                f"{doc_result['summary']}\n\n"
                f"🔴 Pay Instantly via PayPay:\n{paypay_link}\n\n"
                f"📅 Due Date: {doc_result['deadline'] or 'None'}\n"
                f"💰 Amount: ¥{doc_result['amount'] or 'None'}\n"
                f"━━━━━━━━━━━━━━━━━━━\n"
                f"✅ This reminder was archived & generated for your Caregiver Dashboard."
            )
        except Exception as e:
            state.add_log(f"Error handling LINE image: {e}", "danger")
            reply_text = "Sorry, I encountered an error while analyzing your document image. Please try again."
            
        line_bot_api.reply_message(reply_token, TextSendMessage(text=reply_text))

    @handler.add(MessageEvent, message=AudioMessage)
    def handle_audio_message(event):
        save_user_id(event)
        reply_token = event.reply_token
        message_id = event.message.id
        state.add_log("LINE: Received voice message. Downloading...", "info")
        
        try:
            message_content = line_bot_api.get_message_content(message_id)
            audio_bytes = b""
            for chunk in message_content.iter_content():
                audio_bytes += chunk
                
            state.add_log("Audio downloaded. Analyzing for disasters via Gemini...", "info")
            
            # Execute Gemini Audio Analysis
            siren_result = agents.analyze_siren(audio_bytes)
            
            if siren_result.get("is_emergency", False):
                trigger_emergency_flow_sync(siren_result)
                reply_text = (
                    f"⚠️ EMERGENCY SIREN DETECTED!\n"
                    f"━━━━━━━━━━━━━━━━━━━\n"
                    f"🚨 Hazard: {siren_result['alert_type']}\n"
                    f"🔥 Severity: {siren_result['severity']}\n"
                    f"━━━━━━━━━━━━━━━━━━━\n"
                    f"📢 Instructions:\n"
                    f"{siren_result['announcement_summary']}\n\n"
                    f"Please share your live location using the button below so I can calculate your evacuation route."
                )
                quick_reply = QuickReply(items=[
                    QuickReplyButton(action=LocationAction(label="📍 Share Location"))
                ])
                line_bot_api.reply_message(reply_token, TextSendMessage(text=reply_text, quick_reply=quick_reply))
            else:
                state.add_log("Audio memo analyzed: Safe (No threat detected).", "success")
                reply_text = "No emergency sirens or disaster warnings detected in your voice message. You are safe."
                line_bot_api.reply_message(reply_token, TextSendMessage(text=reply_text))
        except Exception as e:
            state.add_log(f"Error handling LINE audio: {e}", "danger")
            reply_text = "Sorry, I had trouble analyzing your voice recording. Please stay safe."
            line_bot_api.reply_message(reply_token, TextSendMessage(text=reply_text))

    @handler.add(MessageEvent, message=VideoMessage)
    def handle_video_message(event):
        save_user_id(event)
        reply_token = event.reply_token
        message_id = event.message.id
        state.add_log("LINE: Received video message. Downloading...", "info")
        
        try:
            message_content = line_bot_api.get_message_content(message_id)
            video_bytes = b""
            for chunk in message_content.iter_content():
                video_bytes += chunk
                
            state.add_log("Video downloaded. Analyzing for threats via Gemini Multimodal...", "info")
            
            # Execute Gemini Multimodal Analysis (re-use siren/threat logic for safety trigger)
            siren_result = agents.analyze_video(video_bytes)
            
            if siren_result.get("is_emergency", False):
                trigger_emergency_flow_sync(siren_result)
                reply_text = (
                    f"⚠️ EMERGENCY WARNING DETECTED IN VIDEO!\n"
                    f"━━━━━━━━━━━━━━━━━━━\n"
                    f"🚨 Hazard: {siren_result['alert_type']}\n"
                    f"🔥 Severity: {siren_result['severity']}\n"
                    f"━━━━━━━━━━━━━━━━━━━\n"
                    f"📢 Action Required:\n"
                    f"{siren_result['announcement_summary']}\n\n"
                    f"Please share your live location using the button below so I can calculate your evacuation route."
                )
                quick_reply = QuickReply(items=[
                    QuickReplyButton(action=LocationAction(label="📍 Share Location"))
                ])
                line_bot_api.reply_message(reply_token, TextSendMessage(text=reply_text, quick_reply=quick_reply))
            else:
                state.add_log("Video analyzed: Safe (No threats visualised).", "success")
                reply_text = "No visible hazards or emergency warnings detected in your video recording. You are safe."
                line_bot_api.reply_message(reply_token, TextSendMessage(text=reply_text))
        except Exception as e:
            state.add_log(f"Error handling LINE video: {e}", "danger")
            reply_text = "Sorry, I had trouble analyzing your video recording. Please stay safe."
            line_bot_api.reply_message(reply_token, TextSendMessage(text=reply_text))

    @handler.add(MessageEvent, message=LocationMessage)
    def handle_location_message(event):
        save_user_id(event)
        reply_token = event.reply_token
        lat = event.message.latitude
        lon = event.message.longitude
        addr = event.message.address
        
        state.last_latitude = lat
        state.last_longitude = lon
        state.add_log(f"LINE: Received location update: {addr} ({lat}, {lon})", "info")
        
        # Determine nearest shelter based on current emergency status or default to general
        hazard = state.active_hazard if state.emergency_mode else "other"
        shelter = find_dynamic_shelter_via_gemini(lat, lon, addr, hazard)
        
        # Calculate dynamic route points
        state.route_coordinates = [
            [lat, lon],
            [(lat + shelter["lat"]) / 2.0, (lon + shelter["lon"]) / 2.0], # mid point
            [shelter["lat"], shelter["lon"]]
        ]
        state.route_steps = shelter["steps"]
        state.add_log(f"Identified nearest shelter: {shelter['name']}. Evacuation route generated.", "success")
        
        maps_link = f"https://www.google.com/maps/dir/?api=1&origin={lat},{lon}&destination={urllib.parse.quote(shelter['name'])}&travelmode=walking"
        
        if state.emergency_mode:
            reply_text = (
                f"📍 SHELTER ROUTE GENERATED!\n"
                f"━━━━━━━━━━━━━━━━━━━\n"
                f"🏠 Safe Shelter:\n"
                f"{shelter['name']}\n"
                f"━━━━━━━━━━━━━━━━━━━\n"
                f"🗺️ Evacuation Route Link:\n{maps_link}\n\n"
                f"🏃 Please proceed immediately. Your location has been shared with your family."
            )
            
            # Generate Pillow visual safety card
            os.makedirs("static/temp", exist_ok=True)
            card_filename = f"card_{event.message.id}.png"
            card_path = f"static/temp/{card_filename}"
            try:
                card_bytes = generate_safety_card_pillow(shelter["name"], hazard, shelter["steps"])
                with open(card_path, "wb") as f:
                    f.write(card_bytes)
                image_url = f"{state.base_url}/dashboard/temp/{card_filename}"
                state.add_log(f"Generated dynamic safety card: {image_url}", "success")
            except Exception as img_err:
                state.add_log(f"Failed to generate safety card: {img_err}", "danger")
                image_url = None
                
            # Generate gTTS vocal reassurance voice note
            audio_filename = f"voice_{event.message.id}.mp3"
            audio_path = f"static/temp/{audio_filename}"
            try:
                voice_text = f"おばあちゃん、落ち着いてください。避難所として{shelter['name']}が選ばれました。地図をLINEに送りましたので、ゆっくり進んでください。家族にも連絡済みです。安心してください。"
                tts = gTTS(text=voice_text, lang='ja')
                tts.save(audio_path)
                audio_url = f"{state.base_url}/dashboard/temp/{audio_filename}"
                state.add_log(f"Generated dynamic TTS voice note: {audio_url}", "success")
            except Exception as tts_err:
                state.add_log(f"Failed to generate voice note: {tts_err}", "danger")
                audio_url = None
                
            # Deliver text + card + voice note to LINE
            messages = [TextSendMessage(text=reply_text)]
            if image_url:
                messages.append(ImageSendMessage(original_content_url=image_url, preview_image_url=image_url))
            if audio_url:
                messages.append(AudioSendMessage(original_content_url=audio_url, duration=11000))
                
            line_bot_api.reply_message(reply_token, messages)
        else:
            reply_text = f"Thank you, received location: {addr}. Dashboard updated. Nearest shelter in case of emergency is {shelter['name']}."
            line_bot_api.reply_message(reply_token, TextSendMessage(text=reply_text))


@app.post("/webhook/line")
async def line_webhook(request: Request, background_tasks: BackgroundTasks):
    """
    Webhook target URL for the LINE Messaging API.
    Handles verification signatures and forwards processing asynchronous.
    """
    signature = request.headers.get("X-Line-Signature", "")
    body = await request.body()
    body_str = body.decode("utf-8")
    
    base_url = str(request.base_url).rstrip("/")
    if base_url.startswith("http://") and "localhost" not in base_url and "127.0.0.1" not in base_url:
        base_url = "https://" + base_url[7:]
    state.base_url = base_url
    
    if not handler:
        state.add_log("LINE Webhook received a request, but credentials are unconfigured.", "warning")
        return "Webhook received (Bypassed due to empty credentials)"
        
    try:
        background_tasks.add_task(run_line_handler, body_str, signature)
    except Exception as e:
        state.add_log(f"Signature error: {e}", "danger")
        raise HTTPException(status_code=400, detail="Signature authentication failed")
        
    return "OK"

def run_line_handler(body_str: str, signature: str):
    try:
        handler.handle(body_str, signature)
    except InvalidSignatureError:
        state.add_log("Invalid request signature. Event rejected.", "danger")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8080, reload=True)
